<a href="https://colab.research.google.com/github/JheniferBritto/analise-dados-atendimentos/blob/main/Python2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [696]:
import pandas as pd

dados = {
    'Paciente': ['Ana', 'Bruno', 'Carlos', 'Daniel', 'Ana', 'Bruno', 'Carlos', 'Ana', 'Marcos'],

    'Data Atendimento': [
        '10/02/2024', 'erro', None, '15/03/2024',
        '32/13/2024', '10-02-2024', '2024/02/10',
        None, '11/02/2024'
    ],

    'Quantidade': [1, '2', None, 100, 2, 'erro', 4, 3, 200],

    'Cidade': ['SP', 'RJ', None, 'SP', '???', 'RJ', 'RJ', 'SP', 'BA'],

    'valor_pago': [100, 250, 150, 750, 100, 400, 320, 200, 500],
    'especialidades':[
    "Triagem", "Teleconsulta", "Sessão Grupo",
    "Home Care", "Avaliação", "Manutenção",
    "Especialista Pleno", "Especialista Sênior", "Alta Complexidade"
]

}

df = pd.DataFrame(dados)

In [697]:
df.head()

  Paciente Data Atendimento Quantidade Cidade  valor_pago especialidades
0      Ana       10/02/2024          1     SP         100        Triagem
1    Bruno             erro          2     RJ         250   Teleconsulta
2   Carlos             None       None   None         150   Sessão Grupo
3   Daniel       15/03/2024        100     SP         750      Home Care
4      Ana       32/13/2024          2    ???         100      Avaliação

In [698]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Paciente          9 non-null      object
 1   Data Atendimento  7 non-null      object
 2   Quantidade        8 non-null      object
 3   Cidade            8 non-null      object
 4   valor_pago        9 non-null      int64
 5   especialidades    9 non-null      object
dtypes: int64(1), object(5)
memory usage: 564.0+ bytes

In [699]:
df.isnull().sum()

Paciente            0
Data Atendimento    2
Quantidade          1
Cidade              1
valor_pago          0
especialidades      0
dtype: int64

In [700]:
df[df.isnull().any(axis=1)]

  Paciente Data Atendimento Quantidade Cidade  valor_pago       especialidades
2   Carlos             None       None   None         150         Sessão Grupo
7      Ana             None          3     SP         200  Especialista Sênior

In [701]:
df['Data Atendimento'].unique() # A coluna Data Atendimento foi removida da Tabela muito valores não veridico e nullo. Essa coluna não vai ser necessária para responder as perguntas.

array(['10/02/2024', 'erro', None, '15/03/2024', '32/13/2024',
       '10-02-2024', '2024/02/10', '11/02/2024'], dtype=object)

In [702]:
df = df.drop('Data Atendimento', axis=1)

In [703]:
df.describe()

       valor_pago
count    9.000000
mean   307.777778
std    214.288227
min    100.000000
25%    150.000000
50%    250.000000
75%    400.000000
max    750.000000

In [704]:
df['Quantidade'] = pd.to_numeric(df['Quantidade'], errors='coerce')
df['Quantidade'] = df['Quantidade'].fillna(df['Quantidade'].median()).astype('int') # De acordo com os dados quantidade existe valores estremo, por tanto foi escolhido a mediana.

In [705]:
df[df.isnull().any(axis=1)]

  Paciente  Quantidade Cidade  valor_pago especialidades
2   Carlos           3   None         150   Sessão Grupo

In [706]:
df['Cidade'] = df['Cidade'].replace('???', 'Desconhecida')

In [707]:
df['Cidade'] = df['Cidade'].fillna('Desconhecida')

In [708]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Paciente        9 non-null      object
 1   Quantidade      9 non-null      int64
 2   Cidade          9 non-null      object
 3   valor_pago      9 non-null      int64
 4   especialidades  9 non-null      object
dtypes: int64(2), object(3)
memory usage: 492.0+ bytes

In [709]:
df['valor_pago'] = df['valor_pago'].astype('float')

In [710]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Paciente        9 non-null      object
 1   Quantidade      9 non-null      int64
 2   Cidade          9 non-null      object
 3   valor_pago      9 non-null      float64
 4   especialidades  9 non-null      object
dtypes: float64(1), int64(1), object(3)
memory usage: 492.0+ bytes

In [711]:
df.columns = df.columns.str.strip().str.title()

In [712]:
df['Valor_Pago'].unique()

array([100., 250., 150., 750., 400., 320., 200., 500.])

In [713]:
df['Quantidade'].unique()

array([  1,   2,   3, 100,   4, 200])

In [714]:
media = df['Valor_Pago'].mean()
media

np.float64(307.77777777777777)

In [715]:
q1 = df['Valor_Pago'].quantile(0.25)
q3 = df['Valor_Pago'].quantile(0.75)

IQR = q3-q1

limite_inferir = q1 -1.5*IQR
limite_superior =q3+1.5*IQR

outlers = df[(df['Valor_Pago'] < limite_inferir)| (df['Valor_Pago'] >  limite_superior)]


print(outlers) # Não mostra nenhum outlers em valor_pago

Empty DataFrame
Columns: [Paciente, Quantidade, Cidade, Valor_Pago, Especialidades]
Index: []

In [716]:
df

  Paciente  Quantidade        Cidade  Valor_Pago       Especialidades
0      Ana           1            SP       100.0              Triagem
1    Bruno           2            RJ       250.0         Teleconsulta
2   Carlos           3  Desconhecida       150.0         Sessão Grupo
3   Daniel         100            SP       750.0            Home Care
4      Ana           2  Desconhecida       100.0            Avaliação
5    Bruno           3            RJ       400.0           Manutenção
6   Carlos           4            RJ       320.0   Especialista Pleno
7      Ana           3            SP       200.0  Especialista Sênior
8   Marcos         200            BA       500.0    Alta Complexidade

In [717]:
q1 =  df['Quantidade'].quantile(0.25)
q3 = df['Quantidade'].quantile(0.75)

IQR = q3-q1

limite_inferir = q1 -1.5*IQR
limite_superior =q3+1.5*IQR

outlers = df[(df['Quantidade'] < limite_inferir)| (df['Quantidade'] >  limite_superior)]

print(outlers) # Na coluna quantidade foi localizado valores que fora da curvas

  Paciente  Quantidade Cidade  Valor_Pago     Especialidades
3   Daniel         100     SP       750.0          Home Care
8   Marcos         200     BA       500.0  Alta Complexidade

Existe desperdício (outliers)? Acho que a pergunta está errado. pq notamos que existe valores que foge dos dados. só que o valor pago está muito pouco. temos que analisar melhor

In [718]:
df['Valor_Atendimento'] =  df['Valor_Pago'] / df['Quantidade']

In [719]:
df.columns

Index(['Paciente', 'Quantidade', 'Cidade', 'Valor_Pago', 'Especialidades',
       'Valor_Atendimento'],
      dtype='object')

In [720]:
df.groupby('Especialidades')['Valor_Atendimento'].sum().round(2)

Especialidades
Alta Complexidade        2.50
Avaliação               50.00
Especialista Pleno      80.00
Especialista Sênior     66.67
Home Care                7.50
Manutenção             133.33
Sessão Grupo            50.00
Teleconsulta           125.00
Triagem                100.00
Name: Valor_Atendimento, dtype: float64

In [721]:
df.columns

Index(['Paciente', 'Quantidade', 'Cidade', 'Valor_Pago', 'Especialidades',
       'Valor_Atendimento'],
      dtype='object')

In [722]:
df.groupby(['Cidade', 'Especialidades']).agg({'Valor_Pago': 'sum', 'Quantidade': 'sum', 'Valor_Atendimento': 'sum'}).sort_values('Quantidade',ascending=False).round(2) # A cidade BA e SP tem uma quantidade grande de atendimento onde o valor por cada pessoa não bate de acordo com a especialidades do profissional. precisamos verificar se os dados estão certo. Ou se tem algo acontecendo e analisar a tabela de preço do profissional. os valores estão fora da curva por isso é um outlers.

                                  Valor_Pago  Quantidade  Valor_Atendimento
Cidade       Especialidades
BA           Alta Complexidade         500.0         200               2.50
SP           Home Care                 750.0         100               7.50
RJ           Especialista Pleno        320.0           4              80.00
             Manutenção                400.0           3             133.33
Desconhecida Sessão Grupo              150.0           3              50.00
SP           Especialista Sênior       200.0           3              66.67
Desconhecida Avaliação                 100.0           2              50.00
RJ           Teleconsulta              250.0           2             125.00
SP           Triagem                   100.0           1             100.00

In [723]:
df.groupby('Cidade')['Valor_Pago'].sum().round(2).sort_values(ascending=False) # A cidade que gera mais valor de acordo com a tabela é sp

Cidade
SP              1050.0
RJ               970.0
BA               500.0
Desconhecida     250.0
Name: Valor_Pago, dtype: float64

In [724]:
df.groupby('Paciente')['Quantidade'].sum()

Paciente
Ana         6
Bruno       5
Carlos      7
Daniel    100
Marcos    200
Name: Quantidade, dtype: int64

In [725]:
df.groupby('Paciente')['Valor_Pago'].sum().round(2)

Paciente
Ana       400.0
Bruno     650.0
Carlos    470.0
Daniel    750.0
Marcos    500.0
Name: Valor_Pago, dtype: float64

In [726]:
df['Valor_Pago'].sum()

np.float64(2770.0)

In [731]:
from scipy.optimize import linprog

c = [-133,-125] # Objetivo peguei somente valores que são veridico especialita.

A = [[3,2]] # quantidade seria restrições de serviço pretando

b = [4] # limite decidir que seja 5

x = [(0, None), (0, None)]

res = linprog(c, A_ub=A, b_ub=b, bounds=x)
print(res.x) # mostra que vale apena investir Teleconsulta

[0. 2.]